/**
 * Partner Service
 * 
 * Service layer for all partner-related API endpoints.
 * Uses the Account API base URL from config.
 */

import config from '../../config/config';

// ============================================================================
// Types
// ============================================================================

export type PartnerId = string;

export interface PartnerProfile {
  id: number;
  partner_user: string;
  partner_id: string | null;
  partner_name: string;
  partner_code: string;
  partner_hq_address: string;
  partner_hq_state: string;
  partner_hq_city: string;
  partner_country: string;
  partner_email: string;
  partner_token_expires_at: string | null;
  created_at: string;
  updated_at: string;
  // JWT tokens returned on OTP verification
  access: string;
  refresh: string;
}

export interface ApiResponse<T = unknown> {
  code: string;
  message: string;
  data: T;
}

export interface Partner {
  id: PartnerId;
  email: string;
  fullName: string;
  status: 'active' | 'pending' | 'invited' | 'revoked';
  createdAt: string;
  updatedAt: string;
}

export interface CreatePartnerPayload {
  email: string;
  fullName: string;
  role?: string;
}

export interface UpdatePartnerPayload {
  email?: string;
  fullName?: string;
  status?: string;
}

export interface CompleteOnboardingPayload {
  partner_user: string;
}

// ── Partner Invite ────────────────────────────────────────────────────────────

export interface InviteRole {
  id: number;
  name: string;
  created_at: string;
  updated_at: string;
}

export interface InviteBranch {
  id: number;
  branch_code: string;
  country: string;
  address: string;
  state: string;
  lga: string;
  lat: string;
  lon: string;
  status: boolean;
  created_at: string;
  updated_at: string;
  partner: number;
  branch_managers: BranchManager[];
}

export interface PartnerInvite {
  id: number;
  email: string;
  first_name: string;
  last_name: string;
  status: boolean;
  two_fa_code?: string | null;
  branch: InviteBranch | null;
  inviting_partner?: string | null;
  invite_role: InviteRole;
  created_at: string;
  updated_at: string;
}

export interface CreateInvitePayload {
  email: string;
  first_name: string;
  last_name: string;
  branch?: string;
  invite_role: string;
}

export interface UpdateInvitePayload {
  email?: string;
  first_name?: string;
  last_name?: string;
  branch?: string;
  invite_role?: string;
  status?: boolean;
}

// ── Role ─────────────────────────────────────────────────────────────────────

export interface Role {
  id: string;
  name: string;
}

// ── Branch Partner ────────────────────────────────────────────────────────────

export interface BranchManager {
  id: number;
  first_name: string;
  last_name: string;
  email: string;
  status: boolean;
  invite_role: number;
}

export interface BranchPartner {
  id: string;
  branch_managers: BranchManager[];
  branch_code: string;
  country: string;
  address: string;
  state: string;
  lga: string;
  lat: string;
  lon: string;
  status: boolean;
  role: string;
  partner: string;
  created_at: string;
  updated_at: string;
}

export interface CreateBranchPayload {
  branch_manager: string[]; // array of invite IDs
  branch_code?: string;     // auto-generated by server
  country?: string;
  address?: string;
  state?: string;
  lga?: string;
  lat?: string;
  lon?: string;
  status?: boolean;
  role?: string;
  partner?: string;
}

export interface UpdateBranchPayload {
  branch_managers?: string[];
  branch_code?: string;
  country?: string;
  address?: string;
  state?: string;
  lga?: string;
  lat?: string;
  lon?: string;
  status?: boolean;
  role?: string;
}

export interface PartnerResponse {
  success: boolean;
  data?: Partner;
  message?: string;
}

export interface PartnersListResponse {
  success: boolean;
  data?: Partner[];
  message?: string;
}

// ============================================================================
// API Base URL
// ============================================================================

const API_BASE_URL = config.api.azapal.baseUrl;
const PARTNER_ENDPOINT = `${API_BASE_URL}/partner`;

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Constructs headers with authorization if token exists
 */
const getHeaders = (contentType = 'application/json'): HeadersInit => {
  const headers: HeadersInit = {
    'Content-Type': contentType,
  };

  // Primary source: explicitly saved auth token
  let token = localStorage.getItem('auth_token');

  // Fallback: access token from the stored partner profile
  if (!token) {
    try {
      const raw = localStorage.getItem('partner_profile');
      if (raw) {
        const profile = JSON.parse(raw);
        token = profile?.access ?? null;
        if (token) localStorage.setItem('auth_token', token);
      }
    } catch {
      // ignore parse errors
    }
  }

  if (token) {
    headers['Authorization'] = `Bearer ${token}`;
  }

  return headers;
};

/**
 * Handles API errors and throws descriptive error messages
 */
const handleError = async (response: Response): Promise<never> => {
  const contentType = response.headers.get('content-type');
  let errorMessage = `HTTP ${response.status}`;

  try {
    if (contentType?.includes('application/json')) {
      const data = await response.json();
      errorMessage = data.message || data.detail || data.error || errorMessage;
    } else {
      const text = await response.text();
      errorMessage = text || errorMessage;
    }
  } catch {
    // ignore parse errors
  }

  throw new Error(errorMessage);
};

/**
 * Attempts to refresh the access token using the stored refresh token.
 * Returns true if successful, false if the refresh token is also expired.
 * On failure, clears all auth state so the user is effectively logged out.
 */
const tryRefreshToken = async (): Promise<boolean> => {
  const refresh = localStorage.getItem('refresh_token');
  if (!refresh) return false;

  try {
    const res = await fetch(`${API_BASE_URL}/token/refresh/`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ refresh }),
    });

    if (!res.ok) {
      clearAuthState();
      return false;
    }

    const data = await res.json();
    const newAccess = data.access;
    if (!newAccess) {
      clearAuthState();
      return false;
    }

    localStorage.setItem('auth_token', newAccess);
    return true;
  } catch {
    clearAuthState();
    return false;
  }
};

const clearAuthState = () => {
  localStorage.removeItem('auth_token');
  localStorage.removeItem('refresh_token');
  localStorage.removeItem('partner_profile');
  // Redirect to login
  window.location.href = '/';
};

const isTokenExpiredError = (body: unknown): boolean => {
  if (!body || typeof body !== 'object') return false;
  const msg: string = (body as any).detail ?? (body as any).message ?? '';
  return msg.toLowerCase().includes('token') && (
    msg.toLowerCase().includes('expired') ||
    msg.toLowerCase().includes('invalid')
  );
};

/**
 * fetch wrapper that automatically retries once after refreshing the access
 * token when the server responds with a token-expired 401.
 */
const fetchWithAuth = async (url: string, options: RequestInit): Promise<Response> => {
  const res = await fetch(url, { ...options, headers: getHeaders(
    (options.headers as Record<string, string>)?.['Content-Type'] ?? 'application/json'
  )});

  if (res.status === 401) {
    // Clone before reading body (body can only be consumed once)
    const cloned = res.clone();
    try {
      const body = await cloned.json();
      if (isTokenExpiredError(body)) {
        const refreshed = await tryRefreshToken();
        if (refreshed) {
          // Retry the original request with the new token
          return fetch(url, { ...options, headers: getHeaders(
            (options.headers as Record<string, string>)?.['Content-Type'] ?? 'application/json'
          )});
        }
      }
    } catch {
      // Could not parse body — fall through to return original response
    }
  }

  return res;
};

// ============================================================================
// Partner API Methods
// ============================================================================

export const partnerService = {
  /**
   * GET /partner
   * Fetch all partners
   */
  async getAllPartners(): Promise<Partner[]> {
    const response = await fetch(PARTNER_ENDPOINT, {
      method: 'GET',
      headers: getHeaders(),
    });

    if (!response.ok) {
      await handleError(response);
    }

    const data: PartnersListResponse = await response.json();
    return data.data || [];
  },

  /**
   * GET /partner/<id>
   * Fetch a single partner by ID
   */
  async getPartnerById(id: PartnerId): Promise<Partner> {
    const response = await fetch(`${PARTNER_ENDPOINT}/${id}`, {
      method: 'GET',
      headers: getHeaders(),
    });

    if (!response.ok) {
      await handleError(response);
    }

    const data: PartnerResponse = await response.json();
    if (!data.data) {
      throw new Error('Partner not found');
    }
    return data.data;
  },

  /**
   * GET /partner/read/by_partner_id/<id>
   * Fetch partner details by partner ID (alternative endpoint)
   */
  async getPartnerByPartnerId(partnerId: PartnerId): Promise<Partner> {
    const response = await fetch(
      `${PARTNER_ENDPOINT}/read/by_partner_id/${partnerId}`,
      {
        method: 'GET',
        headers: getHeaders(),
      }
    );

    if (!response.ok) {
      await handleError(response);
    }

    const data: PartnerResponse = await response.json();
    if (!data.data) {
      throw new Error('Partner not found');
    }
    return data.data;
  },

  /**
   * POST /partner
   * Create a new partner
   */
  async createPartner(payload: CreatePartnerPayload): Promise<Partner> {
    const response = await fetch(PARTNER_ENDPOINT, {
      method: 'POST',
      headers: getHeaders(),
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      await handleError(response);
    }

    const data: PartnerResponse = await response.json();
    if (!data.data) {
      throw new Error('Failed to create partner');
    }
    return data.data;
  },

  /**
   * PUT /partner/<id>
   * Update a partner
   */
  async updatePartner(
    id: PartnerId,
    payload: UpdatePartnerPayload
  ): Promise<Partner> {
    const response = await fetch(`${PARTNER_ENDPOINT}/${id}`, {
      method: 'PUT',
      headers: getHeaders(),
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      await handleError(response);
    }

    const data: PartnerResponse = await response.json();
    if (!data.data) {
      throw new Error('Failed to update partner');
    }
    return data.data;
  },

  /**
   * POST /partner/complete
   * Complete partner onboarding
   */
  async completeOnboarding(payload: CompleteOnboardingPayload, token:string): Promise<Partner> {
    const response = await fetch(`${PARTNER_ENDPOINT}/complete/${token}`, {
      method: 'PUT',
      headers: getHeaders(),
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      await handleError(response);
    }

    const data: PartnerResponse = await response.json();
    if (!data.data) {
      throw new Error('Failed to complete onboarding');
    }
    return data.data;
  },

  /**
   * POST /partner/<id>/resend
   * Resend invite to partner
   */
  async resendInvite(id: PartnerId): Promise<PartnerResponse> {
    const response = await fetch(`${PARTNER_ENDPOINT}/${id}/resend`, {
      method: 'POST',
      headers: getHeaders(),
    });

    if (!response.ok) {
      await handleError(response);
    }

    return response.json();
  },

  /**
   * POST /partner/<id>/revoke
   * Revoke partner invite
   */
  async revokeInvite(id: PartnerId): Promise<PartnerResponse> {
    const response = await fetch(`${PARTNER_ENDPOINT}/${id}/revoke`, {
      method: 'POST',
      headers: getHeaders(),
    });

    if (!response.ok) {
      await handleError(response);
    }

    return response.json();
  },

  /**
   * POST /partner/otp/send
   * Trigger OTP dispatch for a given partner code
   */
  async sendOtp(partnerCode: string): Promise<PartnerResponse> {
    const response = await fetch(`${PARTNER_ENDPOINT}/otp/send/${encodeURIComponent(partnerCode)}`, {
      method: 'GET',
      headers: getHeaders(),
    });

    if (!response.ok) {
      await handleError(response);
    }

    return response.json();
  },

  /**
   * POST /partner/verify-otp/<partner_code>
   * Verify the OTP for a partner login
   */
  async verifyOtp(partnerCode: string, otp: string): Promise<ApiResponse<PartnerProfile>> {
    const response = await fetch(`${PARTNER_ENDPOINT}/verify-otp/${partnerCode}`, {
      method: 'POST',
      headers: getHeaders(),
      body: JSON.stringify({ otp }),
    });

    if (!response.ok) {
      await handleError(response);
    }

    return response.json();
  },

  /**
   * DELETE /partner/<id>
   * Delete a partner (if supported by API)
   */
  async deletePartner(id: PartnerId): Promise<PartnerResponse> {
    const response = await fetch(`${PARTNER_ENDPOINT}/${id}`, {
      method: 'DELETE',
      headers: getHeaders(),
    });

    if (!response.ok) {
      await handleError(response);
    }

    return response.json();
  },
};

export default partnerService;

// ── Endpoints ─────────────────────────────────────────────────────────────────

const INVITE_ENDPOINT = `${API_BASE_URL}/partner-invites`;
const BRANCH_ENDPOINT = `${API_BASE_URL}/branch-partner`;

/**
 * Normalises a list API response to always return an array.
 * Handles bare arrays, { data: [] }, and DRF paginated { results: [] }.
 */
function extractList<T>(raw: unknown): T[] {
  if (Array.isArray(raw)) return raw as T[];
  if (raw && typeof raw === 'object') {
    const obj = raw as Record<string, unknown>;
    if (Array.isArray(obj.data))    return obj.data as T[];
    if (Array.isArray(obj.results)) return obj.results as T[];
  }
  return [];
}

// ── Partner Invite Service ────────────────────────────────────────────────────

export const inviteService = {
  async getAll(): Promise<PartnerInvite[]> {
    const res = await fetchWithAuth(`${INVITE_ENDPOINT}`, {});
    if (!res.ok) await handleError(res);
    return extractList<PartnerInvite>(await res.json());
  },

  async getById(id: string): Promise<PartnerInvite> {
    const res = await fetchWithAuth(`${INVITE_ENDPOINT}/${id}/`, {});
    if (!res.ok) await handleError(res);
    return res.json();
  },

  async create(payload: CreateInvitePayload): Promise<PartnerInvite> {
    const res = await fetchWithAuth(`${INVITE_ENDPOINT}`, {
      method: 'POST',
      body: JSON.stringify(payload),
    });
    if (!res.ok) await handleError(res);
    return res.json();
  },

  async update(id: string, payload: UpdateInvitePayload): Promise<PartnerInvite> {
    const res = await fetchWithAuth(`${INVITE_ENDPOINT}/${id}/`, {
      method: 'PATCH',
      body: JSON.stringify(payload),
    });
    if (!res.ok) await handleError(res);
    return res.json();
  },

  async delete(id: string): Promise<void> {
    const res = await fetchWithAuth(`${INVITE_ENDPOINT}/${id}/`, { method: 'DELETE' });
    if (!res.ok) await handleError(res);
  },
};

// ── Role Service ──────────────────────────────────────────────────────────────

export const roleService = {
  async getAll(): Promise<Role[]> {
    const res = await fetchWithAuth(`${API_BASE_URL}/role`, {});
    if (!res.ok) await handleError(res);
    return extractList<Role>(await res.json());
  },
};

// ── Services ──────────────────────────────────────────────────────────────────

export interface ServiceContent {
  id: number;
  value: string;
  display_text: string;
  order: number;
  created_at: string;
}

export interface ServiceOption {
  id: number;
  label: string;
  element_type: 'checkbox' | 'text_input' | 'select' | 'radio' | string;
  placeholder: string | null;
  required: boolean;
  order: number;
  contents: ServiceContent[];
  created_at: string;
  updated_at: string;
}

export interface Service {
  id: number;
  name: string;
  description: string;
  is_active: boolean;
  options: ServiceOption[];
  created_at: string;
  updated_at: string;
}

export const serviceService = {
  async getAll(): Promise<Service[]> {
    const res = await fetchWithAuth(`${API_BASE_URL}/services`, {});
    if (!res.ok) await handleError(res);
    const raw = await res.json();
    // Response is double-nested: { success, data: { code, message, data: [...] } }
    const inner = raw?.data;
    if (inner && Array.isArray(inner.data)) return inner.data as Service[];
    return extractList<Service>(raw);
  },
};

// ── Branch Partner Service ────────────────────────────────────────────────────

export const branchPartnerService = {
  async getAll(): Promise<BranchPartner[]> {
    const res = await fetchWithAuth(`${BRANCH_ENDPOINT}`, {});
    if (!res.ok) await handleError(res);
    return extractList<BranchPartner>(await res.json());
  },

  async getById(id: string): Promise<BranchPartner> {
    const res = await fetchWithAuth(`${BRANCH_ENDPOINT}/${id}`, {});
    if (!res.ok) await handleError(res);
    return res.json();
  },

  async create(payload: CreateBranchPayload): Promise<BranchPartner> {
    const res = await fetchWithAuth(`${BRANCH_ENDPOINT}`, {
      method: 'POST',
      body: JSON.stringify(payload),
    });
    if (!res.ok) await handleError(res);
    return res.json();
  },

  async update(id: string, payload: UpdateBranchPayload): Promise<BranchPartner> {
    const res = await fetchWithAuth(`${BRANCH_ENDPOINT}/${id}`, {
      method: 'PUT',
      body: JSON.stringify(payload),
    });
    if (!res.ok) await handleError(res);
    return res.json();
  },

  async delete(id: string): Promise<void> {
    const res = await fetchWithAuth(`${BRANCH_ENDPOINT}/${id}`, { method: 'DELETE' });
    if (!res.ok) await handleError(res);
  },
};
