/**
 * Partner Service
 * 
 * Service layer for all partner-related API endpoints.
 * Uses the Account API base URL from config.
 */

import config from '../../config/config';
import type { CargoType } from '../lib/data/logisticsNetwork';

// ============================================================================
// Types
// ============================================================================

export type PartnerId = string;

export interface PartnerProfile {
  id: number;
  partner_user: string;
  partner_id: string | null;
  partner_name: string;
  partner_code: string;
  partner_hq_address: string;
  partner_hq_state: string;
  partner_hq_city: string;
  partner_country: string;
  partner_email: string;
  partner_token_expires_at: string | null;
  created_at: string;
  updated_at: string;
  // JWT tokens returned on OTP verification
  access: string;
  refresh: string;
}

export interface ApiResponse<T = unknown> {
  code: string;
  message: string;
  data: T;
}

export interface Partner {
  id: PartnerId;
  email: string;
  fullName: string;
  status: 'active' | 'pending' | 'invited' | 'revoked';
  createdAt: string;
  updatedAt: string;
}

export interface CreatePartnerPayload {
  email: string;
  fullName: string;
  role?: string;
}

export interface UpdatePartnerPayload {
  email?: string;
  fullName?: string;
  status?: string;
}

export interface CompleteOnboardingPayload {
  partner_user: string;
}

// ── Partner Invite ────────────────────────────────────────────────────────────

export interface InviteRole {
  id: number;
  name: string;
  created_at: string;
  updated_at: string;
}

export interface InviteBranch {
  id: number;
  branch_code: string;
  country: string;
  address: string;
  state: string;
  lga: string;
  lat: string;
  lon: string;
  status: boolean;
  created_at: string;
  updated_at: string;
  partner: number;
  branch_managers: BranchManager[];
}

export interface PartnerInvite {
  id: number;
  email: string;
  first_name: string;
  last_name: string;
  status: boolean;
  two_fa_code?: string | null;
  branch: InviteBranch | null;
  inviting_partner?: string | null;
  invite_role: InviteRole;
  created_at: string;
  updated_at: string;
}

export interface CreateInvitePayload {
  email: string;
  first_name: string;
  last_name: string;
  branch?: string;
  invite_role: string;
}

export interface UpdateInvitePayload {
  email?: string;
  first_name?: string;
  last_name?: string;
  branch?: string;
  invite_role?: string;
  status?: boolean;
}

// ── Role ─────────────────────────────────────────────────────────────────────

export interface Role {
  id: string;
  name: string;
}

// ── Branch Partner ────────────────────────────────────────────────────────────

export interface BranchManager {
  id: number;
  first_name: string;
  last_name: string;
  email: string;
  status: boolean;
  invite_role: number;
}

export interface BranchPartner {
  id: string;
  branch_managers: BranchManager[];
  branch_code: string;
  country: string;
  address: string;
  state: string;
  lga: string;
  lat: string;
  lon: string;
  status: boolean;
  role: string;
  partner: string;
  created_at: string;
  updated_at: string;
}

export interface CreateBranchPayload {
  branch_manager: string[]; // array of invite IDs
  branch_code?: string;     // auto-generated by server
  country?: string;
  address?: string;
  state?: string;
  lga?: string;
  lat?: string;
  lon?: string;
  status?: boolean;
  role?: string;
  partner?: string;
}

export interface UpdateBranchPayload {
  branch_managers?: string[];
  branch_code?: string;
  country?: string;
  address?: string;
  state?: string;
  lga?: string;
  lat?: string;
  lon?: string;
  status?: boolean;
  role?: string;
}

export interface PartnerResponse {
  success: boolean;
  data?: Partner;
  message?: string;
}

export interface PartnersListResponse {
  success: boolean;
  data?: Partner[];
  message?: string;
}

// ============================================================================
// API Base URL
// ============================================================================

const API_BASE_URL = config.api.azapal.baseUrl;
const PARTNER_ENDPOINT = `${API_BASE_URL}/partner`;

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Constructs headers with authorization if token exists
 */
const getHeaders = (contentType = 'application/json'): HeadersInit => {
  const headers: HeadersInit = {
    'Content-Type': contentType,
    'accept': 'application/json',
  };

  // Primary source: explicitly saved partner-owner auth token
  let token = localStorage.getItem('auth_token');

  // Fallback: access token from the stored partner profile
  if (!token) {
    try {
      const raw = localStorage.getItem('partner_profile');
      if (raw) {
        const profile = JSON.parse(raw);
        token = profile?.access ?? null;
        if (token) localStorage.setItem('auth_token', token);
      }
    } catch {
      // ignore parse errors
    }
  }

  // Fallback again: a Tenant Admin/Super Admin employee session (rep_auth_token) —
  // these two roles are routed into the same main-dashboard hooks this file backs
  // (see RequireAuth.tsx), so this is the one place that needs to recognize their
  // token too rather than every hook needing its own dual-session-aware variant.
  if (!token) {
    token = localStorage.getItem('rep_auth_token');
  }

  if (token) {
    headers['Authorization'] = `Bearer ${token}`;
  }

  return headers;
};

/**
 * Extracts the first field-level validation message from a DRF-style error
 * body, e.g. { data: { email: ["already exists."] } } -> "already exists."
 * These are more specific than the generic top-level `message`.
 */
const extractFieldError = (data: unknown): string | null => {
  const errors = (data as Record<string, unknown> | undefined)?.data;
  // Plain-string data — e.g. api_response('01', 'failed', 'You already have a
  // rate for this cargo type') — the top-level `message` is always the generic
  // 'failed' in this convention, so the real text lives here.
  if (typeof errors === 'string' && errors.trim()) return errors;
  if (errors && typeof errors === 'object' && !Array.isArray(errors)) {
    for (const value of Object.values(errors as Record<string, unknown>)) {
      if (Array.isArray(value) && typeof value[0] === 'string') {
        return value[0];
      }
    }
  }
  return null;
};

/**
 * Handles API errors and throws descriptive error messages
 */
const handleError = async (response: Response): Promise<never> => {
  const contentType = response.headers.get('content-type');
  let errorMessage = `HTTP ${response.status}`;

  try {
    if (contentType?.includes('application/json')) {
      const data = await response.json();
      errorMessage = extractFieldError(data) || data.message || data.detail || data.error || errorMessage;
    } else {
      const text = await response.text();
      errorMessage = text || errorMessage;
    }
  } catch {
    // ignore parse errors
  }

  throw new Error(errorMessage);
};

/**
 * Deletes every cookie readable from document.cookie (HttpOnly cookies can't
 * be touched from JS regardless, by design). Uses the standard expiry-based
 * deletion since cookieStore.clear() doesn't exist and isn't supported
 * outside Chromium browsers.
 */
const clearAllCookies = () => {
  document.cookie.split(';').forEach((cookie) => {
    const name = cookie.split('=')[0].trim();
    if (name) {
      document.cookie = `${name}=;expires=Thu, 01 Jan 1970 00:00:00 UTC;path=/;`;
    }
  });
};

const clearAuthState = () => {
  localStorage.removeItem('auth_token');
  localStorage.removeItem('refresh_token');
  localStorage.removeItem('partner_profile');
  // Also clear a rep/employee session — getHeaders() above can source a token
  // from either, so a 401/403 needs to drop both, not just the partner side.
  localStorage.removeItem('rep_auth_token');
  localStorage.removeItem('rep_refresh_token');
  localStorage.removeItem('rep_profile');
  clearAllCookies();
  // Redirect to login
  window.location.href = '/';
};

/**
 * fetch wrapper that treats any 401 as a genuinely expired/invalid session —
 * it clears auth state and forces the user back to login immediately,
 * rather than attempting a silent refresh.
 */
const fetchWithAuth = async (url: string, options: RequestInit): Promise<Response> => {
  const res = await fetch(url, { ...options, headers: getHeaders(
    (options.headers as Record<string, string>)?.['Content-Type'] ?? 'application/json'
  )});

  if (res.status === 401 || res.status === 403) {
    clearAuthState();
  }

  return res;
};

// ============================================================================
// Partner API Methods
// ============================================================================

export const partnerService = {
  /**
   * GET /partner
   * Fetch all partners
   */
  async getAllPartners(): Promise<Partner[]> {
    const response = await fetch(PARTNER_ENDPOINT, {
      method: 'GET',
      headers: getHeaders(),
    });

    if (!response.ok) {
      await handleError(response);
    }

    const data: PartnersListResponse = await response.json();
    return data.data || [];
  },

  /**
   * GET /partner/<id>
   * Fetch a single partner by ID
   */
  async getPartnerById(id: PartnerId): Promise<Partner> {
    const response = await fetch(`${PARTNER_ENDPOINT}/${id}`, {
      method: 'GET',
      headers: getHeaders(),
    });

    if (!response.ok) {
      await handleError(response);
    }

    const data: PartnerResponse = await response.json();
    if (!data.data) {
      throw new Error('Partner not found');
    }
    return data.data;
  },

  /**
   * GET /partner/read/by_partner_id/<id>
   * Fetch partner details by partner ID (alternative endpoint)
   */
  async getPartnerByPartnerId(partnerId: PartnerId): Promise<Partner> {
    const response = await fetch(
      `${PARTNER_ENDPOINT}/read/by_partner_id/${partnerId}`,
      {
        method: 'GET',
        headers: getHeaders(),
      }
    );

    if (!response.ok) {
      await handleError(response);
    }

    const data: PartnerResponse = await response.json();
    if (!data.data) {
      throw new Error('Partner not found');
    }
    return data.data;
  },

  /**
   * POST /partner
   * Create a new partner
   */
  async createPartner(payload: CreatePartnerPayload): Promise<Partner> {
    const response = await fetch(PARTNER_ENDPOINT, {
      method: 'POST',
      headers: getHeaders(),
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      await handleError(response);
    }

    const data: PartnerResponse = await response.json();
    if (!data.data) {
      throw new Error('Failed to create partner');
    }
    return data.data;
  },

  /**
   * PUT /partner/<id>
   * Update a partner
   */
  async updatePartner(
    id: PartnerId,
    payload: UpdatePartnerPayload
  ): Promise<Partner> {
    const response = await fetch(`${PARTNER_ENDPOINT}/${id}`, {
      method: 'PUT',
      headers: getHeaders(),
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      await handleError(response);
    }

    const data: PartnerResponse = await response.json();
    if (!data.data) {
      throw new Error('Failed to update partner');
    }
    return data.data;
  },

  /**
   * POST /partner/complete
   * Complete partner onboarding
   */
  async completeOnboarding(payload: CompleteOnboardingPayload, token:string): Promise<Partner> {
    const response = await fetch(`${PARTNER_ENDPOINT}/complete/${token}`, {
      method: 'PUT',
      headers: getHeaders(),
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      await handleError(response);
    }

    const data: PartnerResponse = await response.json();
    if (!data.data) {
      throw new Error('Failed to complete onboarding');
    }
    return data.data;
  },

  /**
   * POST /partner/<id>/resend
   * Resend invite to partner
   */
  async resendInvite(id: PartnerId): Promise<PartnerResponse> {
    const response = await fetch(`${PARTNER_ENDPOINT}/${id}/resend`, {
      method: 'POST',
      headers: getHeaders(),
    });

    if (!response.ok) {
      await handleError(response);
    }

    return response.json();
  },

  /**
   * POST /partner/<id>/revoke
   * Revoke partner invite
   */
  async revokeInvite(id: PartnerId): Promise<PartnerResponse> {
    const response = await fetch(`${PARTNER_ENDPOINT}/${id}/revoke`, {
      method: 'POST',
      headers: getHeaders(),
    });

    if (!response.ok) {
      await handleError(response);
    }

    return response.json();
  },

  /**
   * POST /partner/otp/send
   * Trigger OTP dispatch for a given partner code
   */
  async sendOtp(partnerCode: string): Promise<PartnerResponse> {
    const response = await fetch(`${PARTNER_ENDPOINT}/otp/send/${encodeURIComponent(partnerCode)}`, {
      method: 'GET',
      headers: getHeaders(),
    });

    if (!response.ok) {
      await handleError(response);
    }

    return response.json();
  },

  /**
   * POST /partner/verify-otp/<partner_code>
   * Verify the OTP for a partner login
   */
  async verifyOtp(partnerCode: string, otp: string): Promise<ApiResponse<PartnerProfile>> {
    const response = await fetch(`${PARTNER_ENDPOINT}/verify-otp/${partnerCode}`, {
      method: 'POST',
      headers: getHeaders(),
      body: JSON.stringify({ otp }),
    });

    if (!response.ok) {
      await handleError(response);
    }

    return response.json();
  },

  /**
   * DELETE /partner/<id>
   * Delete a partner (if supported by API)
   */
  async deletePartner(id: PartnerId): Promise<PartnerResponse> {
    const response = await fetch(`${PARTNER_ENDPOINT}/${id}`, {
      method: 'DELETE',
      headers: getHeaders(),
    });

    if (!response.ok) {
      await handleError(response);
    }

    return response.json();
  },
};

export default partnerService;

// ── Endpoints ─────────────────────────────────────────────────────────────────

const INVITE_ENDPOINT = `${API_BASE_URL}/partner-invites`;
const BRANCH_ENDPOINT = `${API_BASE_URL}/branch-partner`;

/**
 * Normalises a list API response to always return an array.
 * Handles bare arrays, { data: [] }, and DRF paginated { results: [] }.
 */
function extractList<T>(raw: unknown): T[] {
  if (Array.isArray(raw)) return raw as T[];
  if (raw && typeof raw === 'object') {
    const obj = raw as Record<string, unknown>;
    if (Array.isArray(obj.data))    return obj.data as T[];
    if (Array.isArray(obj.results)) return obj.results as T[];
  }
  return [];
}

// ── Partner Invite Service ────────────────────────────────────────────────────

export const inviteService = {
  async getAll(): Promise<PartnerInvite[]> {
    const res = await fetchWithAuth(`${INVITE_ENDPOINT}`, {});
    if (!res.ok) await handleError(res);
    return extractList<PartnerInvite>(await res.json());
  },

  async getById(id: string): Promise<PartnerInvite> {
    const res = await fetchWithAuth(`${INVITE_ENDPOINT}/${id}/`, {});
    if (!res.ok) await handleError(res);
    return res.json();
  },

  async create(payload: CreateInvitePayload): Promise<PartnerInvite> {
    const res = await fetchWithAuth(`${INVITE_ENDPOINT}`, {
      method: 'POST',
      body: JSON.stringify(payload),
    });
    if (!res.ok) await handleError(res);
    return res.json();
  },

  async update(id: string, payload: UpdateInvitePayload): Promise<PartnerInvite> {
    const res = await fetchWithAuth(`${INVITE_ENDPOINT}/${id}/`, {
      method: 'PATCH',
      body: JSON.stringify(payload),
    });
    if (!res.ok) await handleError(res);
    return res.json();
  },

  async delete(id: string): Promise<void> {
    const res = await fetchWithAuth(`${INVITE_ENDPOINT}/${id}/`, { method: 'DELETE' });
    if (!res.ok) await handleError(res);
  },
};

// ── Partner Profile (self-service) ─────────────────────────────────────────────
// Proposed endpoint — see docs/partner-profile-api-contract.md

export interface UpdatePartnerProfilePayload {
  partner_name?: string;
  partner_email?: string;
  partner_hq_address?: string;
  partner_hq_state?: string;
  partner_hq_city?: string;
  partner_country?: string;
}

export const partnerProfileService = {
  async update(payload: UpdatePartnerProfilePayload): Promise<PartnerProfile> {
    const res = await fetchWithAuth(`${PARTNER_ENDPOINT}/profile`, {
      method: 'PUT',
      body: JSON.stringify(payload),
    });
    if (!res.ok) await handleError(res);
    const raw = await res.json();
    return raw.data ?? raw;
  },
};

// ── Rate ──────────────────────────────────────────────────────────────────────

export type RateScope = 'intra' | 'international';

export interface ItemCategory {
  id: number;
  name: string;
  code: string;
}

export type ShippingMode = 'walk' | 'bicycle' | 'motorcycle' | 'car' | 'mini_van' | 'van' | 'mini_truck' | 'truck';

export interface Rate {
  id: number;
  region: string;
  scope: RateScope;
  category: ItemCategory | null;
  shipping_mode: ShippingMode | null;
  price: number;
  window: string;
  pickup_service: string;
  created_at: string;
  updated_at: string;
}

export interface CreateRatePayload {
  region: string;
  scope?: RateScope;
  category_id?: number | null;
  shipping_mode?: ShippingMode | null;
  price: number;
  window?: string;
  pickup_service?: string;
}

export interface UpdateRatePayload {
  region?: string;
  scope?: RateScope;
  category_id?: number | null;
  shipping_mode?: ShippingMode | null;
  price?: number;
  window?: string;
  pickup_service?: string;
}

const RATE_ENDPOINT = `${PARTNER_ENDPOINT}/rates`;

export const rateService = {
  async getAll(): Promise<Rate[]> {
    const res = await fetchWithAuth(`${RATE_ENDPOINT}`, {});
    if (!res.ok) await handleError(res);
    return extractList<Rate>(await res.json());
  },

  async create(payload: CreateRatePayload): Promise<Rate> {
    const res = await fetchWithAuth(`${RATE_ENDPOINT}`, {
      method: 'POST',
      body: JSON.stringify(payload),
    });
    if (!res.ok) await handleError(res);
    const raw = await res.json();
    return raw.data ?? raw;
  },

  async update(id: number, payload: UpdateRatePayload): Promise<Rate> {
    const res = await fetchWithAuth(`${RATE_ENDPOINT}/${id}/`, {
      method: 'PUT',
      body: JSON.stringify(payload),
    });
    if (!res.ok) await handleError(res);
    const raw = await res.json();
    return raw.data ?? raw;
  },

  async delete(id: number): Promise<void> {
    const res = await fetchWithAuth(`${RATE_ENDPOINT}/${id}/`, { method: 'DELETE' });
    if (!res.ok) await handleError(res);
  },
};

// ── Item Categories (lookup for Rate.category) ─────────────────────────────────

const ITEM_CATEGORY_ENDPOINT = `${API_BASE_URL}/item-categories`;

export const itemCategoryService = {
  async getAll(): Promise<ItemCategory[]> {
    const res = await fetchWithAuth(`${ITEM_CATEGORY_ENDPOINT}`, {});
    if (!res.ok) await handleError(res);
    return extractList<ItemCategory>(await res.json());
  },
};

// ── Rate Cards (route / cargo type / delivery method) ─────────────────────────
// Proposed endpoints — see docs/partner-rate-cards-api-contract.md

export type RateCardStatus = 'Active' | 'Inactive';

export interface RouteRateCard {
  id: number;
  origin_state: string;
  destination_state: string;
  cargo_type: CargoType;
  price: number;
  status: RateCardStatus;
  created_at: string;
  updated_at: string;
}

export interface CreateRouteRateCardPayload {
  origin_state: string;
  destination_state: string;
  cargo_type?: CargoType;
  price: number;
  status?: RateCardStatus;
}

export type UpdateRouteRateCardPayload = Partial<CreateRouteRateCardPayload>;

const ROUTE_RATE_ENDPOINT = `${PARTNER_ENDPOINT}/route-rates`;

export const routeRateCardService = {
  async getAll(): Promise<RouteRateCard[]> {
    const res = await fetchWithAuth(`${ROUTE_RATE_ENDPOINT}`, {});
    if (!res.ok) await handleError(res);
    return extractList<RouteRateCard>(await res.json());
  },

  async create(payload: CreateRouteRateCardPayload): Promise<RouteRateCard> {
    const res = await fetchWithAuth(`${ROUTE_RATE_ENDPOINT}`, {
      method: 'POST',
      body: JSON.stringify(payload),
    });
    if (!res.ok) await handleError(res);
    const raw = await res.json();
    return raw.data ?? raw;
  },

  async update(id: number, payload: UpdateRouteRateCardPayload): Promise<RouteRateCard> {
    const res = await fetchWithAuth(`${ROUTE_RATE_ENDPOINT}/${id}/`, {
      method: 'PUT',
      body: JSON.stringify(payload),
    });
    if (!res.ok) await handleError(res);
    const raw = await res.json();
    return raw.data ?? raw;
  },

  async delete(id: number): Promise<void> {
    const res = await fetchWithAuth(`${ROUTE_RATE_ENDPOINT}/${id}/`, { method: 'DELETE' });
    if (!res.ok) await handleError(res);
  },
};

export interface CargoRateCard {
  id: number;
  cargo_type: CargoType;
  base_price: number;
  price_per_kg: number;
  status: RateCardStatus;
  created_at: string;
  updated_at: string;
}

export interface CreateCargoRateCardPayload {
  cargo_type: CargoType;
  base_price: number;
  price_per_kg: number;
  status?: RateCardStatus;
}

export type UpdateCargoRateCardPayload = Partial<CreateCargoRateCardPayload>;

const CARGO_RATE_ENDPOINT = `${PARTNER_ENDPOINT}/cargo-rates`;

export const cargoRateCardService = {
  async getAll(): Promise<CargoRateCard[]> {
    const res = await fetchWithAuth(`${CARGO_RATE_ENDPOINT}`, {});
    if (!res.ok) await handleError(res);
    return extractList<CargoRateCard>(await res.json());
  },

  async create(payload: CreateCargoRateCardPayload): Promise<CargoRateCard> {
    const res = await fetchWithAuth(`${CARGO_RATE_ENDPOINT}`, {
      method: 'POST',
      body: JSON.stringify(payload),
    });
    if (!res.ok) await handleError(res);
    const raw = await res.json();
    return raw.data ?? raw;
  },

  async update(id: number, payload: UpdateCargoRateCardPayload): Promise<CargoRateCard> {
    const res = await fetchWithAuth(`${CARGO_RATE_ENDPOINT}/${id}/`, {
      method: 'PUT',
      body: JSON.stringify(payload),
    });
    if (!res.ok) await handleError(res);
    const raw = await res.json();
    return raw.data ?? raw;
  },

  async delete(id: number): Promise<void> {
    const res = await fetchWithAuth(`${CARGO_RATE_ENDPOINT}/${id}/`, { method: 'DELETE' });
    if (!res.ok) await handleError(res);
  },
};

export type DeliveryMethod = 'Walk' | 'Bicycle' | 'Motorcycle' | 'Car' | 'Van' | 'Truck';

export const DELIVERY_METHODS: DeliveryMethod[] = ['Walk', 'Bicycle', 'Motorcycle', 'Car', 'Van', 'Truck'];

export interface DeliveryMethodRateCard {
  id: number;
  method: DeliveryMethod;
  price: number;
  status: RateCardStatus;
  created_at: string;
  updated_at: string;
}

export interface CreateDeliveryMethodRateCardPayload {
  method: DeliveryMethod;
  price: number;
  status?: RateCardStatus;
}

export type UpdateDeliveryMethodRateCardPayload = Partial<CreateDeliveryMethodRateCardPayload>;

const DELIVERY_METHOD_RATE_ENDPOINT = `${PARTNER_ENDPOINT}/delivery-method-rates`;

export const deliveryMethodRateCardService = {
  async getAll(): Promise<DeliveryMethodRateCard[]> {
    const res = await fetchWithAuth(`${DELIVERY_METHOD_RATE_ENDPOINT}`, {});
    if (!res.ok) await handleError(res);
    return extractList<DeliveryMethodRateCard>(await res.json());
  },

  async create(payload: CreateDeliveryMethodRateCardPayload): Promise<DeliveryMethodRateCard> {
    const res = await fetchWithAuth(`${DELIVERY_METHOD_RATE_ENDPOINT}`, {
      method: 'POST',
      body: JSON.stringify(payload),
    });
    if (!res.ok) await handleError(res);
    const raw = await res.json();
    return raw.data ?? raw;
  },

  async update(id: number, payload: UpdateDeliveryMethodRateCardPayload): Promise<DeliveryMethodRateCard> {
    const res = await fetchWithAuth(`${DELIVERY_METHOD_RATE_ENDPOINT}/${id}/`, {
      method: 'PUT',
      body: JSON.stringify(payload),
    });
    if (!res.ok) await handleError(res);
    const raw = await res.json();
    return raw.data ?? raw;
  },

  async delete(id: number): Promise<void> {
    const res = await fetchWithAuth(`${DELIVERY_METHOD_RATE_ENDPOINT}/${id}/`, { method: 'DELETE' });
    if (!res.ok) await handleError(res);
  },
};

// ── Pairing Routes ──────────────────────────────────────────────────────────────

export type PairingFrequency = 'one_time' | 'daily' | 'weekly' | 'monthly';

export interface PairingRoute {
  id: number;
  partner: number;
  partner_name: string;
  origin_state: string;
  destination_state: string;
  frequency: PairingFrequency;
  preferred_date: string;
  cargo_type: CargoType;
  min_budget: number;
  max_budget: number;
  is_open_for_joining: boolean;
  created_at: string;
  updated_at: string;
}

export interface CreatePairingRoutePayload {
  origin_state: string;
  destination_state: string;
  frequency?: PairingFrequency;
  preferred_date: string;
  cargo_type?: CargoType;
  min_budget: number;
  max_budget: number;
}

export type UpdatePairingRoutePayload = Partial<CreatePairingRoutePayload>;

export interface BudgetTargetPreviewPayload {
  weight_kg: number;
  include_last_mile?: boolean;
  last_mile_actual_cost?: number;
  item_count?: number;
}

export interface BudgetTargetPreview {
  estimated_price_per_kg: number;
  cargo_fee: number;
  last_mile_fee: number;
  total: number;
  businesses_for_half_min_budget: number;
  businesses_for_half_max_budget: number;
}

const PAIRING_ROUTE_ENDPOINT = `${PARTNER_ENDPOINT}/pairing-routes`;

export const pairingRouteService = {
  async getAll(): Promise<PairingRoute[]> {
    const res = await fetchWithAuth(`${PAIRING_ROUTE_ENDPOINT}`, {});
    if (!res.ok) await handleError(res);
    return extractList<PairingRoute>(await res.json());
  },

  async create(payload: CreatePairingRoutePayload): Promise<PairingRoute> {
    const res = await fetchWithAuth(`${PAIRING_ROUTE_ENDPOINT}`, {
      method: 'POST',
      body: JSON.stringify(payload),
    });
    if (!res.ok) await handleError(res);
    const raw = await res.json();
    return raw.data ?? raw;
  },

  async update(id: number, payload: UpdatePairingRoutePayload): Promise<PairingRoute> {
    const res = await fetchWithAuth(`${PAIRING_ROUTE_ENDPOINT}/${id}/`, {
      method: 'PUT',
      body: JSON.stringify(payload),
    });
    if (!res.ok) await handleError(res);
    const raw = await res.json();
    return raw.data ?? raw;
  },

  async delete(id: number): Promise<void> {
    const res = await fetchWithAuth(`${PAIRING_ROUTE_ENDPOINT}/${id}/`, { method: 'DELETE' });
    if (!res.ok) await handleError(res);
  },

  async getBudgetTarget(id: number, payload: BudgetTargetPreviewPayload): Promise<BudgetTargetPreview> {
    const res = await fetchWithAuth(`${PAIRING_ROUTE_ENDPOINT}/${id}/budget-target/`, {
      method: 'POST',
      body: JSON.stringify(payload),
    });
    if (!res.ok) await handleError(res);
    const raw = await res.json();
    return raw.data ?? raw;
  },
};

// ── Role Service ──────────────────────────────────────────────────────────────

export const roleService = {
  async getAll(): Promise<Role[]> {
    const res = await fetchWithAuth(`${API_BASE_URL}/role`, {});
    if (!res.ok) await handleError(res);
    return extractList<Role>(await res.json());
  },
};

// ── Services ──────────────────────────────────────────────────────────────────

export interface ServiceContent {
  id: number;
  value: string;
  display_text: string;
  order: number;
  created_at: string;
}

export interface ServiceOption {
  id: number;
  label: string;
  element_type: 'checkbox' | 'text_input' | 'select' | 'select_dropdown' | 'radio' | string;
  placeholder: string | null;
  required: boolean;
  order: number;
  contents: ServiceContent[];
  created_at: string;
  updated_at: string;
}

export interface Service {
  id: number;
  name: string;
  description: string;
  is_active: boolean;
  options: ServiceOption[];
  created_at: string;
  updated_at: string;
}

export const serviceService = {
  async getAll(): Promise<Service[]> {
    const res = await fetchWithAuth(`${API_BASE_URL}/services`, {});
    if (!res.ok) await handleError(res);
    const raw = await res.json();
    // Response is double-nested: { success, data: { code, message, data: [...] } }
    const inner = raw?.data;
    if (inner && Array.isArray(inner.data)) return inner.data as Service[];
    return extractList<Service>(raw);
  },
};

// ── Branch Partner Service ────────────────────────────────────────────────────

export const branchPartnerService = {
  async getAll(): Promise<BranchPartner[]> {
    const res = await fetchWithAuth(`${BRANCH_ENDPOINT}`, {});
    if (!res.ok) await handleError(res);
    return extractList<BranchPartner>(await res.json());
  },

  async getById(id: string): Promise<BranchPartner> {
    const res = await fetchWithAuth(`${BRANCH_ENDPOINT}/${id}`, {});
    if (!res.ok) await handleError(res);
    const raw = await res.json();
    return raw.data ?? raw;
  },

  async create(payload: CreateBranchPayload): Promise<BranchPartner> {
    const res = await fetchWithAuth(`${BRANCH_ENDPOINT}`, {
      method: 'POST',
      body: JSON.stringify(payload),
    });
    if (!res.ok) await handleError(res);
    return res.json();
  },

  async update(id: string, payload: UpdateBranchPayload): Promise<BranchPartner> {
    const res = await fetchWithAuth(`${BRANCH_ENDPOINT}/${id}`, {
      method: 'PUT',
      body: JSON.stringify(payload),
    });
    if (!res.ok) await handleError(res);
    return res.json();
  },

  async delete(id: string): Promise<void> {
    const res = await fetchWithAuth(`${BRANCH_ENDPOINT}/${id}`, { method: 'DELETE' });
    if (!res.ok) await handleError(res);
  },
};

// ── Dashboard Stats ───────────────────────────────────────────────────────────

export interface DashboardOrderStats {
  total: number;
  pending: number;
  completed: number;
  failed: number;
  total_customers: number;
}

export interface DashboardBranchManager {
  id: number;
  first_name: string;
  last_name: string;
  email: string;
  status: boolean;
  invite_role: number;
}

export interface DashboardBranch {
  id: number;
  branch_managers: DashboardBranchManager[];
  branch_code: string;
  country: string;
  address: string;
  state: string;
  lga: string;
  lat: string;
  lon: string;
  status: boolean;
  created_at: string;
  updated_at: string;
  partner: number;
}

export interface DashboardBranchStats {
  total: number;
  first_three: DashboardBranch[];
}

export interface DashboardServiceStats {
  total_active: number;
}

export interface DashboardStats {
  orders: DashboardOrderStats;
  branches: DashboardBranchStats;
  services: DashboardServiceStats;
  monthly_delivery_analytics: unknown[];
}

export const dashboardService = {
  async getStats(): Promise<DashboardStats> {
    const res = await fetchWithAuth(`${API_BASE_URL}/dashboard/stats`, {});
    if (!res.ok) await handleError(res);
    const raw: ApiResponse<DashboardStats> = await res.json();
    return raw.data;
  },
};

// ── Transactions ──────────────────────────────────────────────────────────────

export type TransactionStatus = 'pending' | 'approved' | 'shipped' | 'delivered' | 'canceled' | string;
export type TransactionPaymentStatus = 'approved' | 'pending' | 'failed' | 'reversed' | 'refund' | string;

export interface TransactionParty {
  id: number;
  name: string;
  phone: string | null;
  is_verified: boolean;
  rating: number | null;
}

export interface TransactionBranchInfo {
  id: number;
  branch_code: string;
  state: string;
  is_verified: boolean;
  rating: number | null;
}

export interface TransactionStop {
  id: number;
  stop_type: 'pickup' | 'delivery' | string;
  sequence?: number;
  address: string;
  // Live data confirms these are frequently null (e.g. shared-location or
  // manually-typed addresses that never got geocoded/reverse-geocoded) —
  // never assume presence without a guard.
  state: string | null;
  country: string | null;
  lat: number | null;
  lon: number | null;
  created_at?: string;
}

export interface Transaction {
  id: number;
  sender_id: string;
  status: TransactionStatus;
  payment_status: TransactionPaymentStatus;
  total_amount: number | null;
  delivery_method: string;
  reference?: string | null;
  session_code?: string | null;
  dispatch_business_id_no?: TransactionParty | null;
  vendor_business_id_no?: TransactionParty | null;
  branch: TransactionBranchInfo | null;
  driver: TransactionParty | null;
  stops: TransactionStop[];
  confirmed_at: string | null;
  created_at: string;
  updated_at?: string;
  pickup_code?: string | null;
  delivery_option?: string | null;
  delivery_instructions?: string | null;
  remarks?: string | null;
  [key: string]: unknown;
}

export interface TransactionsQuery {
  status?: TransactionStatus;
  payment_status?: TransactionPaymentStatus;
  page?: number;
  page_size?: number;
}

export interface TransactionsPage {
  count: number;
  next: string | null;
  previous: string | null;
  results: Transaction[];
}

export const transactionService = {
  async getAll(query: TransactionsQuery = {}): Promise<TransactionsPage> {
    const params = new URLSearchParams();
    if (query.status) params.set('status', query.status);
    if (query.payment_status) params.set('payment_status', query.payment_status);
    if (query.page) params.set('page', String(query.page));
    if (query.page_size) params.set('page_size', String(query.page_size));
    const qs = params.toString();

    const res = await fetchWithAuth(
      `${PARTNER_ENDPOINT}/transactions${qs ? `?${qs}` : ''}`,
      {}
    );
    if (!res.ok) await handleError(res);
    const raw = await res.json();

    return {
      count: raw.count ?? 0,
      next: raw.next ?? null,
      previous: raw.previous ?? null,
      results: extractList<Transaction>(raw.results),
    };
  },
};

// ── Logistics network (transactions/all + transactions/pairable) ──────────────
// Richer-query sibling of `transactionService` above — same underlying orders
// and the same response shape (`Transaction`), but with extra filters
// (country/state/confirmed) and a `pairable` grouping endpoint that
// `transactionService` doesn't expose.

export interface LogisticsTransaction {
  id: number;
  sender_id: string;
  status: TransactionStatus;
  payment_status: TransactionPaymentStatus;
  total_amount: number | null;
  reference?: string | null;
  // Named for the underlying DB column, but this is the fulfilling partner
  // for the order, not the sender/dispatcher. Null until a partner picks up
  // the order.
  dispatch_business_id_no: TransactionParty | null;
  vendor_business_id_no?: TransactionParty | null;
  branch: TransactionBranchInfo | null;
  driver: TransactionParty | null;
  stops: TransactionStop[];
  created_at: string;
  updated_at?: string;
  pickup_code?: string | null;
  travel_mode?: string | null;
  [key: string]: unknown;
}

export interface LogisticsTransactionsQuery {
  country?: string;
  state?: string;
  status?: TransactionStatus;
  payment_status?: TransactionPaymentStatus;
  confirmed?: boolean;
  page?: number;
  page_size?: number;
}

export interface LogisticsTransactionsPage {
  count: number;
  next: string | null;
  previous: string | null;
  results: LogisticsTransaction[];
}

export interface PairableGroup {
  country: string;
  state: string;
  order_count: number;
  orders: LogisticsTransaction[];
}

const buildLogisticsQuery = (query: LogisticsTransactionsQuery): URLSearchParams => {
  const params = new URLSearchParams();
  if (query.country) params.set('country', query.country);
  if (query.state) params.set('state', query.state);
  if (query.status) params.set('status', query.status);
  if (query.payment_status) params.set('payment_status', query.payment_status);
  if (query.confirmed != null) params.set('confirmed', String(query.confirmed));
  if (query.page) params.set('page', String(query.page));
  if (query.page_size) params.set('page_size', String(query.page_size));
  return params;
};

export const logisticsService = {
  async getAll(query: LogisticsTransactionsQuery = {}): Promise<LogisticsTransactionsPage> {
    const qs = buildLogisticsQuery(query).toString();
    const res = await fetchWithAuth(`${PARTNER_ENDPOINT}/transactions/all${qs ? `?${qs}` : ''}`, {});
    if (!res.ok) await handleError(res);
    const raw = await res.json();

    return {
      count: raw.count ?? 0,
      next: raw.next ?? null,
      previous: raw.previous ?? null,
      results: extractList<LogisticsTransaction>(raw.results),
    };
  },

  async getPairable(query: LogisticsTransactionsQuery = {}): Promise<PairableGroup[]> {
    const qs = buildLogisticsQuery(query).toString();
    const res = await fetchWithAuth(`${PARTNER_ENDPOINT}/transactions/pairable${qs ? `?${qs}` : ''}`, {});
    if (!res.ok) await handleError(res);
    const json: ApiResponse<{ groups: PairableGroup[] }> = await res.json();
    return json.data?.groups ?? [];
  },
};

// ── Partner Service Selection ─────────────────────────────────────────────────

export const partnerServicesService = {
  async getSelected(): Promise<Service[]> {
    const res = await fetchWithAuth(`${PARTNER_ENDPOINT}/services`, {});
    if (!res.ok) await handleError(res);
    return extractList<Service>(await res.json());
  },

  async updateSelected(serviceIds: number[]): Promise<Service[]> {
    const res = await fetchWithAuth(`${PARTNER_ENDPOINT}/services`, {
      method: 'PUT',
      body: JSON.stringify({ service_ids: serviceIds }),
    });
    if (!res.ok) await handleError(res);
    return extractList<Service>(await res.json());
  },
};

// ── Partner Activity Logs ──────────────────────────────────────────────────────

export type LogAction = 'CREATE' | 'UPDATE' | 'DELETE' | 'VIEW' | string;
export type ActorType = 'partner' | 'employee' | 'user' | string;

export interface PartnerLog {
  id: number;
  user_id: string;
  actor_type: ActorType;
  action: LogAction;
  level: string;
  resource: string;
  object_id: string | null;
  payload: unknown;
  ip_address: string;
  partner: number;
  branch: number | null;
  created_at: string;
}

export interface PartnerLogsQuery {
  branch_id?: string | number;
  action?: LogAction;
  resource?: string;
  actor_type?: ActorType;
  user_id?: string;
  page?: number;
  page_size?: number;
}

export interface PartnerLogsPage {
  count: number;
  next: string | null;
  previous: string | null;
  results: PartnerLog[];
}

export const partnerLogService = {
  async getAll(query: PartnerLogsQuery = {}): Promise<PartnerLogsPage> {
    const params = new URLSearchParams();
    if (query.branch_id) params.set('branch_id', String(query.branch_id));
    if (query.action) params.set('action', query.action);
    if (query.resource) params.set('resource', query.resource);
    if (query.actor_type) params.set('actor_type', query.actor_type);
    if (query.user_id) params.set('user_id', query.user_id);
    if (query.page) params.set('page', String(query.page));
    if (query.page_size) params.set('page_size', String(query.page_size));
    const qs = params.toString();

    const res = await fetchWithAuth(`${PARTNER_ENDPOINT}/logs${qs ? `?${qs}` : ''}`, {});
    if (!res.ok) await handleError(res);
    const raw = await res.json();

    return {
      count: raw.count ?? 0,
      next: raw.next ?? null,
      previous: raw.previous ?? null,
      results: extractList<PartnerLog>(raw.results),
    };
  },
};

// ── Partner Sessions ────────────────────────────────────────────────────────────

export interface PartnerSession {
  id: number;
  actor_type: ActorType;
  partner: number;
  branch: number | null;
  employee: number | null;
  ip_address: string;
  user_agent: string;
  created_at: string;
}

export interface PartnerSessionsQuery {
  branch_id?: string | number;
  actor_type?: ActorType;
  employee_id?: string | number;
  page?: number;
  page_size?: number;
}

export interface PartnerSessionsPage {
  count: number;
  next: string | null;
  previous: string | null;
  results: PartnerSession[];
}

export const partnerSessionService = {
  async getAll(query: PartnerSessionsQuery = {}): Promise<PartnerSessionsPage> {
    const params = new URLSearchParams();
    if (query.branch_id) params.set('branch_id', String(query.branch_id));
    if (query.actor_type) params.set('actor_type', query.actor_type);
    if (query.employee_id) params.set('employee_id', String(query.employee_id));
    if (query.page) params.set('page', String(query.page));
    if (query.page_size) params.set('page_size', String(query.page_size));
    const qs = params.toString();

    const res = await fetchWithAuth(`${PARTNER_ENDPOINT}/sessions${qs ? `?${qs}` : ''}`, {});
    if (!res.ok) await handleError(res);
    const raw = await res.json();

    return {
      count: raw.count ?? 0,
      next: raw.next ?? null,
      previous: raw.previous ?? null,
      results: extractList<PartnerSession>(raw.results),
    };
  },
};

// ── Payout split ────────────────────────────────────────────────────────────────
// Real, backend-integrated (unlike the dummy financial module below) — see
// modules/business/partner_splits.py in azapal-backend, which itself proxies to
// wallet-service. How a settled amount fans out across this partner's own
// dispatchers/stakeholders; distinct from partner-financial-module-api-contract.md's
// "Wallet" resource (a partner's own balance/ledger), which this doesn't touch.

export interface SplitMember {
  external_user_id: string;
  label: string | null;
  share_percent: number;
}

export interface SplitConfig {
  partnerRef: string;
  name: string | null;
  members: SplitMember[];
}

const SPLIT_ENDPOINT = `${PARTNER_ENDPOINT}/split`;

function toSplitMember(raw: any): SplitMember {
  return {
    external_user_id: raw.externalUserId,
    label: raw.label ?? null,
    share_percent: Number(raw.sharePercent),
  };
}

export const splitService = {
  /** Returns null if this identity (partner default, or one branch) hasn't configured a split yet. */
  async get(branchId?: number | null): Promise<SplitConfig | null> {
    const qs = branchId ? `?branch_id=${branchId}` : '';
    const res = await fetchWithAuth(`${SPLIT_ENDPOINT}${qs}`, {});
    if (!res.ok) await handleError(res);
    const raw = await res.json();
    if (!raw.data) return null;
    return {
      partnerRef: raw.data.partnerRef,
      name: raw.data.name ?? null,
      members: (raw.data.members ?? []).map(toSplitMember),
    };
  },

  /** Replaces the full member list for this identity. Shares must sum to exactly 100 (validated server-side). */
  async save(name: string | undefined, members: SplitMember[], branchId?: number | null): Promise<SplitConfig> {
    const res = await fetchWithAuth(SPLIT_ENDPOINT, {
      method: 'PUT',
      body: JSON.stringify({
        name,
        branch_id: branchId || undefined,
        members: members.map((m) => ({
          external_user_id: m.external_user_id,
          label: m.label || undefined,
          share_percent: m.share_percent,
        })),
      }),
    });
    if (!res.ok) await handleError(res);
    const raw = await res.json();
    return {
      partnerRef: raw.data.partnerRef,
      name: raw.data.name ?? null,
      members: (raw.data.members ?? []).map(toSplitMember),
    };
  },
};

// ── Wallet ──────────────────────────────────────────────────────────────────────
// Real, backed by wallet-service via modules/business/partner_wallet.py in
// azapal-backend — see docs/partner-financial-module-api-contract.md.

export interface WalletBalance {
  balance: number;
  pending_balance: number;
  currency: string;
  updated_at: string | null;
}

export type WalletTransactionType = 'credit' | 'debit';
export type WalletTransactionCategory = 'delivery_earning' | 'payout' | 'fee' | 'adjustment' | 'top_up';

export interface WalletTransaction {
  id: number | null;
  type: WalletTransactionType;
  category: WalletTransactionCategory;
  amount: number;
  // wallet-service doesn't store a running balance per transaction — always null,
  // not fabricated. Render a "—" for this, don't compute a fake running total.
  balance_after: number | null;
  description: string;
  reference: string;
  // wallet-service has no concept of azapal's own delivery Transaction model —
  // always null from the real backend.
  related_transaction_id: number | null;
  created_at: string;
}

export interface WalletTransactionsQuery {
  page?: number;
  page_size?: number;
  branch_id?: number | null;
}

export interface WalletTransactionsPage {
  count: number;
  next: boolean;
  previous: boolean;
  results: WalletTransaction[];
}

// The banks Paystack actually supports for dedicated-account creation — a much
// shorter, specific list than "all Nigerian banks" (historically just Wema Bank
// and Titan Trust Bank via Paystack's DVA program). provider_slug is what must be
// sent back as CreateVirtualAccountPayload.bank_name — Paystack's dedicated-account
// API takes a slug ("wema-bank"), not a display name.
export interface BankProvider {
  provider_slug: string;
  bank_id: number;
  bank_name: string;
}

const WALLET_ENDPOINT = `${PARTNER_ENDPOINT}/wallet`;

export const walletService = {
  async getBalance(branchId?: number | null): Promise<WalletBalance> {
    const qs = branchId ? `?branch_id=${branchId}` : '';
    const res = await fetchWithAuth(`${WALLET_ENDPOINT}/balance${qs}`, {});
    if (!res.ok) await handleError(res);
    const raw = await res.json();
    return raw.data ?? raw;
  },

  async getTransactions(query: WalletTransactionsQuery = {}): Promise<WalletTransactionsPage> {
    const params = new URLSearchParams();
    if (query.page) params.set('page', String(query.page));
    if (query.page_size) params.set('page_size', String(query.page_size));
    if (query.branch_id) params.set('branch_id', String(query.branch_id));
    const qs = params.toString();

    const res = await fetchWithAuth(`${WALLET_ENDPOINT}/transactions${qs ? `?${qs}` : ''}`, {});
    if (!res.ok) await handleError(res);
    const raw = await res.json();

    return {
      count: raw.count ?? 0,
      next: !!raw.next,
      previous: !!raw.previous,
      results: extractList<WalletTransaction>(raw.results),
    };
  },

  async getProviders(): Promise<BankProvider[]> {
    const res = await fetchWithAuth(`${WALLET_ENDPOINT}/providers`, {});
    if (!res.ok) await handleError(res);
    return extractList<BankProvider>(await res.json());
  },

  /** Whether this partner has opened a dedicated account anywhere — the partner-level
   * default, or any branch. Drives the Financials intro-vs-tabbed gate, now that an
   * account can live under any of several branch-scoped identities. */
  async hasAnyAccount(): Promise<boolean> {
    const res = await fetchWithAuth(`${WALLET_ENDPOINT}/has-account`, {});
    if (!res.ok) await handleError(res);
    const raw = await res.json();
    return !!(raw.data ?? raw)?.has_account;
  },
};

// ── Virtual Accounts ───────────────────────────────────────────────────────────
// Real, backed by wallet-service's Paystack dedicated-virtual-account integration.
// Addressed by account_number, not a numeric id — wallet-service never returns
// one (see wallet-service's src/wallet/routes.ts serializeAccount).

export type VirtualAccountStatus = 'Active' | 'Inactive';

export type WalletReason = 'customer_collections' | 'branch_operations' | 'payroll' | 'savings' | 'refunds' | 'loan_repayment';

export const WALLET_REASONS: { value: WalletReason; label: string; description: string }[] = [
  { value: 'customer_collections', label: 'Customer Collections', description: 'Collect payments directly from your customers.' },
  { value: 'branch_operations', label: 'Branch Operations', description: 'Day-to-day running costs for a specific branch.' },
  { value: 'payroll', label: 'Payroll & Salaries', description: 'Set aside funds for staff pay.' },
  { value: 'savings', label: 'Business Savings', description: "Hold funds you're setting aside." },
  { value: 'refunds', label: 'Customer Refunds', description: 'A dedicated account for issuing refunds.' },
  { value: 'loan_repayment', label: 'Loan Repayment', description: 'Repaying a loan or credit facility.' },
];

export const WALLET_REASON_LABELS: Record<WalletReason, string> = Object.fromEntries(
  WALLET_REASONS.map((r) => [r.value, r.label])
) as Record<WalletReason, string>;


export interface VirtualAccount {
  account_number: string;
  reason: WalletReason | null;
  bank_name: string;
  account_name: string;
  status: VirtualAccountStatus;
  created_at: string | null;
}

export interface CreateVirtualAccountPayload {
  reason: WalletReason;
  // A BankProvider's provider_slug (e.g. "wema-bank"), not a display name —
  // that's what Paystack's dedicated-account API actually expects.
  bank_name?: string;
  // Omitted (or null) means the partner-level default account, not tied to any branch.
  branch_id?: number | null;
}

const WALLET_ACCOUNTS_ENDPOINT = `${WALLET_ENDPOINT}/accounts`;

export const virtualAccountService = {
  async getAll(branchId?: number | null): Promise<VirtualAccount[]> {
    const qs = branchId ? `?branch_id=${branchId}` : '';
    const res = await fetchWithAuth(`${WALLET_ACCOUNTS_ENDPOINT}${qs}`, {});
    if (!res.ok) await handleError(res);
    return extractList<VirtualAccount>(await res.json());
  },

  async create(payload: CreateVirtualAccountPayload): Promise<VirtualAccount> {
    const res = await fetchWithAuth(`${WALLET_ACCOUNTS_ENDPOINT}`, {
      method: 'POST',
      body: JSON.stringify(payload),
    });
    if (!res.ok) await handleError(res);
    const raw = await res.json();
    return raw.data ?? raw;
  },

  async deactivate(accountNumber: string): Promise<VirtualAccount> {
    const res = await fetchWithAuth(`${WALLET_ACCOUNTS_ENDPOINT}/${encodeURIComponent(accountNumber)}/deactivate`, {
      method: 'PATCH',
    });
    if (!res.ok) await handleError(res);
    const raw = await res.json();
    return raw.data ?? raw;
  },
};

// ── Invoices ────────────────────────────────────────────────────────────────────
// Real, greenfield Django models (no wallet-service involvement) — see
// modules/business/partner_invoices.py in azapal-backend. Branch-scoped: a
// branch-employee token only sees/creates their own branch's invoices, a
// partner-owner token sees all (optionally filtered by branch_id).

export type InvoiceStatus = 'draft' | 'sent' | 'paid' | 'overdue' | 'void';

export interface InvoiceLineItem {
  description: string;
  quantity: number;
  unit_price: number;
}

export interface Invoice {
  id: number;
  invoice_number: string;
  branch: number | null;
  customer_name: string;
  customer_email: string | null;
  customer_phone: string | null;
  customer_address: string | null;
  related_transaction: number | null;
  line_items: InvoiceLineItem[];
  subtotal: number;
  total: number;
  status: InvoiceStatus;
  due_date: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface CreateInvoicePayload {
  branch_id: number;
  customer_name: string;
  customer_email?: string | null;
  customer_phone?: string | null;
  customer_address?: string | null;
  related_transaction_id?: number | null;
  line_items: InvoiceLineItem[];
  due_date?: string | null;
  notes?: string | null;
}

export type UpdateInvoicePayload = Partial<Omit<CreateInvoicePayload, 'branch_id' | 'related_transaction_id'>> & { status?: InvoiceStatus };

const INVOICE_ENDPOINT = `${PARTNER_ENDPOINT}/invoices`;

// Django's DecimalField fields serialize as strings ("15000.00") — normalized to
// real numbers here so nothing downstream has to know that.
function normalizeInvoice(raw: any): Invoice {
  return { ...raw, subtotal: Number(raw.subtotal), total: Number(raw.total) };
}

export const invoiceService = {
  async getAll(branchId?: number): Promise<Invoice[]> {
    const qs = branchId ? `?branch_id=${branchId}` : '';
    const res = await fetchWithAuth(`${INVOICE_ENDPOINT}${qs}`, {});
    if (!res.ok) await handleError(res);
    return extractList<any>(await res.json()).map(normalizeInvoice);
  },

  async create(payload: CreateInvoicePayload): Promise<Invoice> {
    const res = await fetchWithAuth(`${INVOICE_ENDPOINT}`, {
      method: 'POST',
      body: JSON.stringify(payload),
    });
    if (!res.ok) await handleError(res);
    const raw = await res.json();
    return normalizeInvoice(raw.data ?? raw);
  },

  async update(id: number, payload: UpdateInvoicePayload): Promise<Invoice> {
    const res = await fetchWithAuth(`${INVOICE_ENDPOINT}/${id}/`, {
      method: 'PUT',
      body: JSON.stringify(payload),
    });
    if (!res.ok) await handleError(res);
    const raw = await res.json();
    return normalizeInvoice(raw.data ?? raw);
  },

  async delete(id: number): Promise<void> {
    const res = await fetchWithAuth(`${INVOICE_ENDPOINT}/${id}/`, { method: 'DELETE' });
    if (!res.ok) await handleError(res);
  },
};

// ── Receipts ────────────────────────────────────────────────────────────────────
// Real, greenfield — see modules/business/partner_receipts.py in azapal-backend.
// Same branch-scoping rules as invoices. Creating one with related_invoice_id set
// marks that invoice paid server-side, atomically with the receipt's creation.

export type ReceiptPaymentMethod = 'bank_transfer' | 'card' | 'cash' | 'wallet';

export interface Receipt {
  id: number;
  receipt_number: string;
  branch: number | null;
  customer_name: string;
  amount: number;
  payment_method: ReceiptPaymentMethod;
  payment_reference: string | null;
  related_invoice: number | null;
  related_transaction: number | null;
  issued_at: string;
  created_at: string;
}

export interface CreateReceiptPayload {
  branch_id: number;
  customer_name: string;
  amount: number;
  payment_method: ReceiptPaymentMethod;
  payment_reference?: string | null;
  related_invoice_id?: number | null;
  related_transaction_id?: number | null;
}

const RECEIPT_ENDPOINT = `${PARTNER_ENDPOINT}/receipts`;

function normalizeReceipt(raw: any): Receipt {
  return { ...raw, amount: Number(raw.amount) };
}

export const receiptService = {
  async getAll(branchId?: number): Promise<Receipt[]> {
    const qs = branchId ? `?branch_id=${branchId}` : '';
    const res = await fetchWithAuth(`${RECEIPT_ENDPOINT}${qs}`, {});
    if (!res.ok) await handleError(res);
    return extractList<any>(await res.json()).map(normalizeReceipt);
  },

  async create(payload: CreateReceiptPayload): Promise<Receipt> {
    const res = await fetchWithAuth(`${RECEIPT_ENDPOINT}`, {
      method: 'POST',
      body: JSON.stringify(payload),
    });
    if (!res.ok) await handleError(res);
    const raw = await res.json();
    return normalizeReceipt(raw.data ?? raw);
  },

  async delete(id: number): Promise<void> {
    const res = await fetchWithAuth(`${RECEIPT_ENDPOINT}/${id}/`, { method: 'DELETE' });
    if (!res.ok) await handleError(res);
  },
};
