// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-variants/CodeFirst.tsx": () => import("../components/mockups/login-variants/CodeFirst.tsx"),
  "./components/mockups/login-variants/Immersive.tsx": () => import("../components/mockups/login-variants/Immersive.tsx"),
  "./components/mockups/login-variants/Stepped.tsx": () => import("../components/mockups/login-variants/Stepped.tsx")
};
